# Generated by Django 2.2.7 on 2019-11-20 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='board',
        ),
    ]
