# Generated by Django 2.2.7 on 2019-11-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20191120_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='board',
            new_name='article',
        ),
    ]
